name: invoice_pdf_generate
description: Invoice PDF Generator (Web + Mobile)
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ">=3.1.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # PDF generation
  pdf: ^3.11.0

  # Mobile file handling
  path_provider: ^2.1.1
  open_file: ^3.3.2

  # Optional (if using icons)
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/

